services:
  - type: web
    name: venom-bot-v1
    env: node
    buildCommand: |
      npm install
      npm install -g pm2
    startCommand: pm2 start src/index.js --name venom-bot
    envVars:
      - key: NODE_ENV
        value: production
      - key: FB_EMAIL
        sync: false
      - key: FB_PASSWORD
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: PORT
        value: "3000"
      - key: PREFIX
        value: "!"
    healthCheckPath: /
    autoDeploy: true
    plan: free 