services:
  - type: web
    name: sarthak-messenger-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PAGE_ACCESS_TOKEN
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: PREFIX
        value: "!"
      - key: PORT
        value: "3000" 